#!/bin/bash

equation="$1"

shift 1

while getopts 'y:d:z:s:' opt; do
	case "$opt" in
		y ) yeq="${OPTARG%;*}"
			y="${OPTARG#*;}";;

		d ) detail=$OPTARG;;
		z ) zeq="${OPTARG%;*}"
			z="${OPTARG#*;}";;
		s ) start="$OPTARG";;
	esac
done

fact() {
	declare -i number=$1 result=1

	while [ $number -gt 1 ]; do
		result="$((result * number))"
		number="$((number - 1))"
		#echo "for the number: $1 factorial is: $result"
	done

	echo $result
}


series=$start

#1 = +, 0 = -

for i in $(seq $detail); do	
	part="$equation"
	part="${part//y/$y}"


	part="${part//z/$z}"

	for factExp in $(echo "$part" | egrep -o "[0-9]{1,}!"); do
		factRes=$(fact ${factExp%!})

		part="${part//$factExp/$factRes}"
	done

	series="$series$part"

	#Execute user defined y equation
	y="$(echo ${yeq//y/$y} | bc)"
	z="$(echo "${zeq//z/$z}" | bc)"

done
	echo "$series"